/**
 * DATOS ESTÁTICOS DE ARTÍCULOS — RPP Interactivo
 * ================================================
 * Este archivo reemplaza el parsing dinámico de archivos .md con gray-matter.
 * Razón: gray-matter falla intermitentemente en entornos de producción/browser
 * al no tener el polyfill de `buffer` disponible, causando que todos los artículos
 * aparezcan como "ANÓNIMO / SIN TÍTULO".
 *
 * Al tener los datos aquí, son resueltos en BUILD TIME por Vite y siempre
 * están disponibles, sin importar el entorno, OS o forma de despliegue.
 */

import type { ArticleData } from './contentLoader';

export const ARTICLES_STATIC: ArticleData[] = [
  {
    id: '3153',
    title: 'Experiencias de discriminación basada en la apariencia física de estudiantes universitarios',
    subtitle: 'La Academia frente a la Discriminación',
    author: 'Ramos-Solís, Sáenz-González, Burnes-Garza & Elizondo-García',
    date: 'Mayo 2024',
    tag: 'Discriminación Educativa',
    metric: 12,
    volume: 'Vol. 38',
    abstract: 'Estudio fenomenológico sobre cómo el color de piel, tatuajes y masa corporal operan como mecanismos de exclusión académica en una universidad privada de élite mexicana.',
    doi: '10.21555/rpp.v38.3153',
    interactUrl: '#',
    icon: 'Search',
    color: 'bg-[#3b82f6]',
    text: 'text-white',
    accent: '#0f172a',
    keywords: ['discriminación', 'apariencia', 'universidad', 'estigma', 'salud mental', 'clasismo'],
    hasInteractive: true,
    body: 'Estudio fenomenológico sobre cómo el color de piel, tatuajes y masa corporal operan como mecanismos de exclusión académica en una universidad privada de élite mexicana.',
  },
  {
    id: '3198',
    title: 'Learning Information and Communication Technologies in active aging: A qualitative study in Buenos Aires',
    subtitle: 'TIC en el Envejecimiento Activo',
    author: 'Hernández-Silvera, Pécora & Núñez',
    date: 'Noviembre 2024',
    tag: 'Educomunicación',
    metric: 95,
    volume: 'Vol. 39',
    abstract: 'Estudio cualitativo (Grounded Theory) en Buenos Aires sobre cómo el aprendizaje móvil previene el aislamiento social mediante Teoría TRIC.',
    doi: '10.21555/rpp.3198',
    interactUrl: '#',
    icon: 'Phone',
    color: 'bg-[#f59e0b]',
    text: 'text-black',
    accent: '#0f172a',
    keywords: ['envejecimiento', 'tic', 'buenos aires', 'tric', 'adultos mayores', 'educomunicación'],
    hasInteractive: true,
    body: 'Estudio cualitativo (Grounded Theory) en Buenos Aires sobre cómo el aprendizaje móvil previene el aislamiento social mediante Teoría TRIC.',
  },
  {
    id: '3214',
    title: 'La innovación pedagógica y su aporte en la formación de bachilleres técnicos agropecuarios para implementar prácticas sostenibles',
    subtitle: 'Prácticas Agrícolas Sostenibles',
    author: 'Dueñas Basurto & Zambrano Vera',
    date: 'Febrero 2025',
    tag: 'Desarrollo Sostenible',
    metric: 119,
    volume: 'Vol. 39',
    abstract: 'Estudio cuasiexperimental sobre la inyección de TIC y apps móviles en la educación de bachilleres técnicos agropecuarios rurales en Manabí.',
    doi: '10.21555/rpp.3214',
    interactUrl: '#',
    icon: 'Sparkles',
    color: 'bg-[#16a34a]',
    text: 'text-white',
    accent: '#facc15',
    keywords: ['agropecuario', 'innovación', 'sostenibilidad', 'ecuador', 'manabí', 'rural'],
    hasInteractive: true,
    body: 'Estudio cuasiexperimental sobre la inyección de TIC y apps móviles en la educación de bachilleres técnicos agropecuarios rurales en Manabí.',
  },
  {
    id: '3290',
    title: 'Challenges in hybrid learning at a university in Southwestern Colombia',
    subtitle: 'El Desafío Multimodal en Superior',
    author: 'Roldán-Morales & Torres-Tovar',
    date: 'Julio 2026',
    tag: 'Aprendizaje Híbrido',
    metric: 89,
    volume: 'Vol. 41',
    abstract: 'Exploración fenomenológica sobre los desafíos pedagógicos y tecnológicos del aprendizaje híbrido en la educación superior colombiana.',
    doi: '10.21555/rpp.3290',
    interactUrl: '#',
    icon: 'Activity',
    color: 'bg-[#0a0a0a]',
    text: 'text-white',
    accent: '#00d2ff',
    keywords: ['aprendizaje híbrido', 'multimodal', 'educación superior', 'fenomenológico', 'colombia'],
    hasInteractive: true,
    body: 'Exploración fenomenológica sobre los desafíos pedagógicos y tecnológicos del aprendizaje híbrido en la educación superior colombiana.',
  },
  {
    id: '3378',
    title: 'Estrategias didácticas para fomentar la participación activa en entornos virtuales mediante paisajes de aprendizaje',
    subtitle: 'Estrategias Didácticas mediante Paisajes de Aprendizaje',
    author: 'S. Saborío-Taylor et al.',
    date: 'Febrero 2026',
    tag: 'Paisajes',
    metric: 85,
    volume: 'Vol. 42',
    abstract: 'Investigación sobre cómo los paisajes de aprendizaje fomentan la participación activa en foros de posgrado, pasando del 33.3% al 57.1% de interacción.',
    doi: '10.21134/rpcp.v2026i1.3378',
    interactUrl: '#',
    icon: 'Activity',
    color: 'bg-[#6C63FF]',
    text: 'text-white',
    accent: '#00D9FF',
    keywords: ['paisajes de aprendizaje', 'participación', 'foros', 'posgrado', 'interacción'],
    hasInteractive: true,
    body: 'Investigación sobre cómo los paisajes de aprendizaje fomentan la participación activa en foros de posgrado, pasando del 33.3% al 57.1% de interacción.',
  },
  {
    id: '3411',
    title: 'Mantenerse en la escuela: desafiliación en un bachillerato tecnológico',
    subtitle: 'Predictores de permanencia en el CETis 74',
    author: 'Jiménez-Moreno & Feria-Juárez',
    date: 'Agosto 2025',
    tag: 'Deserción Escolar',
    metric: 87,
    volume: 'Vol. 41',
    abstract: 'Análisis de variables asociadas a la desafiliación/deserción escolar en CETis 74 mediante regresión logística. Hallazgo central: 28% de deserción y la paradoja del capital digital.',
    doi: '10.21555/rpp.3411',
    interactUrl: '#',
    icon: 'Brain',
    color: 'bg-[#7c3aed]',
    text: 'text-white',
    accent: '#c4b5fd',
    keywords: ['deserción', 'bachillerato', 'tecnológico', 'regresión logística', 'desafiliación'],
    hasInteractive: true,
    body: 'Análisis de variables asociadas a la desafiliación/deserción escolar en CETis 74 mediante regresión logística. Hallazgo central: 28% de deserción y la paradoja del capital digital.',
  },
  {
    id: '3412',
    title: 'Descubriendo competencias blandas en estudiantes de secundaria: exploración y reflexiones',
    subtitle: 'Descubriendo competencias blandas en estudiantes secundarios',
    author: 'Hernández-Silvera et al.',
    date: 'Septiembre 2025',
    tag: 'Competencias Blandas',
    metric: 86,
    volume: 'Vol. 41',
    abstract: 'Exploración de validez y confiabilidad de un inventario piloto de competencias blandas (n=228) en el AMBA, Argentina. Brechas por NSE, género y metodologías activas.',
    doi: '10.21555/rpp.3412',
    interactUrl: '#',
    icon: 'Activity',
    color: 'bg-[#059669]',
    text: 'text-white',
    accent: '#6ee7b7',
    keywords: ['competencias blandas', 'secundaria', 'abp', 'argentina', 'habilidades interpersonales'],
    hasInteractive: true,
    body: 'Exploración de validez y confiabilidad de un inventario piloto de competencias blandas (n=228) en el AMBA, Argentina. Brechas por NSE, género y metodologías activas.',
  },
  {
    id: '3453',
    title: 'Experiencias docentes respecto al abordaje del consumo de drogas en establecimientos educacionales secundarios',
    subtitle: 'Abordaje del Consumo en Escuelas',
    author: 'Inostroza-Fuentes et al.',
    date: 'Agosto 2026',
    tag: 'Estudio Fenomenológico',
    metric: 93,
    volume: 'Vol. 40',
    abstract: 'Investigación cualitativa sobre las experiencias de profesores jefes en el sur de Chile ante el consumo de drogas y las tensiones sociopolíticas.',
    doi: '10.21555/rpp.3453',
    interactUrl: '#',
    icon: 'BookOpen',
    color: 'bg-[#0a0618]',
    text: 'text-white',
    accent: '#ff6b9d',
    keywords: ['drogas', 'docentes', 'chile', 'fenomenológico', 'consumo', 'escuelas'],
    hasInteractive: true,
    body: 'Investigación cualitativa sobre las experiencias de profesores jefes en el sur de Chile ante el consumo de drogas y las tensiones sociopolíticas.',
  },
  {
    id: '3454',
    title: 'Inclusión y cultura de paz en la universidad: percepciones de estudiantes en contexto de violencia delictiva',
    subtitle: 'La Academia frente a la Delincuencia',
    author: 'Ramos-Ramírez & Márquez-Cabellos',
    date: 'Agosto 2025',
    tag: 'Violencia y Educación',
    metric: 200,
    volume: 'Vol. 40',
    abstract: 'Estudio de vulnerabilidad en la Universidad de Colima (ciudad más violenta del mundo) analizando si la cultura de paz existe más allá del discurso frente a la criminalidad activa.',
    doi: '10.21555/rpp.3454',
    interactUrl: '#',
    icon: 'ShieldAlert',
    color: 'bg-[#ef4444]',
    text: 'text-white',
    accent: '#1e1b4b',
    keywords: ['violencia', 'paz', 'inclusión', 'colima', 'criminalidad', 'víctimas'],
    hasInteractive: true,
    body: 'Estudio de vulnerabilidad en la Universidad de Colima (ciudad más violenta del mundo) analizando si la cultura de paz existe más allá del discurso frente a la criminalidad activa.',
  },
  {
    id: '3455',
    title: 'Dimensión personal para la cultura de paz en la formación inicial docente',
    subtitle: 'Formación Docente',
    author: 'Chan-Chi & Poot-May',
    date: 'Marzo 2026',
    tag: 'Paz',
    metric: 80,
    volume: 'Vol. 42',
    abstract: 'Análisis sobre la importancia de la dimensión personal en la construcción de una cultura de paz dentro de los entornos educativos.',
    doi: '10.21134/rpcp.v2026i1.3455',
    interactUrl: '#',
    icon: 'BookOpen',
    color: 'bg-[#2D6A4F]',
    text: 'text-white',
    accent: '#B7E4C7',
    keywords: ['cultura de paz', 'formación docente', 'dimensión personal', 'educación'],
    hasInteractive: true,
    body: 'Análisis sobre la importancia de la dimensión personal en la construcción de una cultura de paz dentro de los entornos educativos.',
  },
  {
    id: '3467',
    title: 'Ciberacoso entre estudiantes universitarios en la postpandemia: comportamientos agresivos y prevención',
    subtitle: 'Prevención en Educación Superior',
    author: 'Vallejos-Parás et al.',
    date: 'Abril 2026',
    tag: 'Ciberacoso',
    metric: 88,
    volume: 'Vol. 42',
    abstract: 'Estudio predictivo mediante modelo Logit para determinar la probabilidad de ciberacoso y estrategias de prevención basadas en la provocación.',
    doi: '10.21134/rpcp.v2026i1.3467',
    interactUrl: '#',
    icon: 'Activity',
    color: 'bg-[#0f172a]',
    text: 'text-white',
    accent: '#ef4444',
    keywords: ['ciberacoso', 'postpandemia', 'prevención', 'logit', 'educación superior'],
    hasInteractive: true,
    body: 'Estudio predictivo mediante modelo Logit para determinar la probabilidad de ciberacoso y estrategias de prevención basadas en la provocación.',
  },
  {
    id: '3476',
    title: 'Docentes e inclusión educativa en la educación media superior: hallazgos de una revisión sistemática (2015-2025)',
    subtitle: 'Docentes y Educación Media Superior',
    author: 'Pacheco-Gómez & Cisneros-Cohernour',
    date: 'Mayo 2026',
    tag: 'Revisión Sistemática',
    metric: 85,
    volume: 'Vol. 41',
    abstract: 'Revisión sistemática sobre las barreras y facilitadores de la inclusión educativa desde la perspectiva docente.',
    doi: '10.21555/rpp.3476',
    interactUrl: '#',
    icon: 'GraduationCap',
    color: 'bg-[#4338ca]',
    text: 'text-white',
    accent: '#10b981',
    keywords: ['inclusión', 'educación media superior', 'revisión sistemática', 'docentes'],
    hasInteractive: true,
    body: 'Revisión sistemática sobre las barreras y facilitadores de la inclusión educativa desde la perspectiva docente.',
  },
  {
    id: '3497',
    title: 'Liderazgo docente y formación del carácter: claves para la transformación educativa en Paraguay',
    subtitle: 'Docente y Formación del Carácter en Paraguay',
    author: 'Servín-Mendieta, Rivas-Benítez & Riveros-Lesmo',
    date: 'Noviembre 2026',
    tag: 'Liderazgo Educativo',
    metric: 84,
    volume: 'Vol. 41',
    abstract: 'Estudio teórico-documental sobre cómo el liderazgo docente y la formación del carácter pueden transformar el sistema educativo paraguayo, superando el modelo administrativo tradicional.',
    doi: '10.21555/rpp.3497',
    interactUrl: '#',
    icon: 'BookOpen',
    color: 'bg-[#b45309]',
    text: 'text-white',
    accent: '#fcd34d',
    keywords: ['liderazgo docente', 'formación del carácter', 'paraguay', 'educación en valores', 'transformación educativa'],
    hasInteractive: true,
    body: 'Estudio teórico-documental sobre cómo el liderazgo docente y la formación del carácter pueden transformar el sistema educativo paraguayo, superando el modelo administrativo tradicional.',
  },
  {
    id: '3508',
    title: 'Las actitudes docentes frente a la inclusión educativa del TEA',
    subtitle: 'Actitudes Docentes ante la Inclusión del TEA',
    author: 'Gallardo-Herrerías',
    date: 'Noviembre 2025',
    tag: 'Inclusión Educativa',
    metric: 90,
    volume: 'Vol. 41',
    abstract: 'Estudio cualitativo comparativo España-Ecuador sobre actitudes del profesorado hacia la inclusión educativa de estudiantes con Trastorno del Espectro Autista.',
    doi: '10.21555/rpp.3508',
    interactUrl: '#',
    icon: 'Heart',
    color: 'bg-[#0d9488]',
    text: 'text-white',
    accent: '#fbbf24',
    keywords: ['tea', 'autismo', 'inclusión educativa', 'actitudes docentes', 'españa', 'ecuador'],
    hasInteractive: true,
    body: 'Estudio cualitativo comparativo España-Ecuador sobre actitudes del profesorado hacia la inclusión educativa de estudiantes con Trastorno del Espectro Autista.',
  },
  {
    id: '3543',
    title: 'Prácticas docentes para el desarrollo de la escritura académica en estudiantes normalistas',
    subtitle: 'Prácticas Docentes y Escritura Académica',
    author: 'Ríos-Higuera & Sotomayor-Andrade',
    date: 'Enero 2027',
    tag: 'Escritura Académica',
    metric: 88,
    volume: 'Vol. 41',
    abstract: 'Estudio cualitativo en una Escuela Normal Superior (México) sobre cómo 14 docentes conceptualizan, asignan, evalúan y acompañan la escritura académica de sus estudiantes normalistas.',
    doi: '10.21555/rpp.3543',
    interactUrl: '#',
    icon: 'Brain',
    color: 'bg-[#0369a1]',
    text: 'text-white',
    accent: '#7dd3fc',
    keywords: ['escritura académica', 'normalistas', 'prácticas docentes', 'méxico', 'escuela normal'],
    hasInteractive: true,
    body: 'Estudio cualitativo en una Escuela Normal Superior (México) sobre cómo 14 docentes conceptualizan, asignan, evalúan y acompañan la escritura académica de sus estudiantes normalistas.',
  },
  {
    id: '3549',
    title: 'Teorías pedagógicas en la Nueva Escuela Mexicana. Apuntes para la educación primaria',
    subtitle: 'Teorías Pedagógicas en la Nueva Escuela Mexicana',
    author: 'C.A. Quintero-Macías & C. Bautista-Villalaz',
    date: 'Enero 2026',
    tag: 'Arqueología Pedagógica',
    metric: 88,
    volume: 'Vol. 42',
    abstract: 'Análisis crítico sobre cómo la NEM retoma principios pedagógicos de Rousseau, Pestalozzi, Dewey y Freire como innovación radical.',
    doi: '10.21134/rpcp.v2026i1.3549',
    interactUrl: '#',
    icon: 'GraduationCap',
    color: 'bg-[#e81e61]',
    text: 'text-white',
    accent: '#fccb06',
    keywords: ['nueva escuela mexicana', 'rousseau', 'pestalozzi', 'dewey', 'freire', 'pedagogía'],
    hasInteractive: true,
    body: 'Análisis crítico sobre cómo la NEM retoma principios pedagógicos de Rousseau, Pestalozzi, Dewey y Freire como innovación radical.',
  },
  {
    id: '3557',
    title: 'Educación jurídica en la era digital: tensiones, resistencias y oportunidades',
    subtitle: 'Gamificación en la Educación Jurídica',
    author: 'Philippe Prince-Galbán et al.',
    date: 'Abril 2026',
    tag: 'Gamificación',
    metric: 94,
    volume: 'Vol. 41',
    abstract: 'Estudio sobre la brecha entre la formación jurídica tradicional y las demandas tecnológicas modernas.',
    doi: '10.21134/rpcp.v2026i1.3557',
    interactUrl: '#',
    icon: 'Brain',
    color: 'bg-[#2563eb]',
    text: 'text-white',
    accent: '#fef08a',
    keywords: ['derecho digital', 'gamificación', 'educación jurídica', 'tecnología'],
    hasInteractive: true,
    body: 'Estudio sobre la brecha entre la formación jurídica tradicional y las demandas tecnológicas modernas.',
  },
  {
    id: '3562',
    title: 'Jóvenes universitarias y su transición a la maternidad: formación, retos y crianza',
    subtitle: 'Jóvenes Universitarias y Transición a la Maternidad',
    author: 'Rodríguez-Calderón-de-la-Barca',
    date: 'Diciembre 2025',
    tag: 'Maternidad Universitaria',
    metric: 89,
    volume: 'Vol. 41',
    abstract: 'Estudio cualitativo en la UPN 153 Ecatepec sobre los retos de jóvenes madres universitarias. Hallazgo central: 8 de 12 interrumpen estudios, no por falta de voluntad, sino por ausencia de políticas institucionales de cuidado.',
    doi: '10.21555/rpp.3562',
    interactUrl: '#',
    icon: 'Heart',
    color: 'bg-[#be185d]',
    text: 'text-white',
    accent: '#fbcfe8',
    keywords: ['maternidad universitaria', 'desigualdad educativa', 'estigma', 'bourdieu', 'goffman', 'méxico'],
    hasInteractive: true,
    body: 'Estudio cualitativo en la UPN 153 Ecatepec sobre los retos de jóvenes madres universitarias.',
  },
  {
    id: '3570',
    title: 'Análisis de la formación docente para el desarrollo del pensamiento crítico',
    subtitle: 'Pensamiento Crítico en Formación Docente',
    author: 'García-Martínez & Reyes-Cabrera',
    date: 'Noviembre 2025',
    tag: 'Revisión Sistemática',
    metric: 89,
    volume: 'Vol. 41',
    abstract: 'Análisis de 15 estudios empíricos (2015-2025) sobre los procesos formativos de docentes en pensamiento crítico para educación preescolar.',
    doi: '10.21555/rpp.3570',
    interactUrl: '#',
    icon: 'Brain',
    color: 'bg-[#0f172a]',
    text: 'text-white',
    accent: '#38bdf8',
    keywords: ['pensamiento crítico', 'formación docente', 'preescolar', 'revisión sistemática', 'prisma'],
    hasInteractive: true,
    body: 'Análisis de 15 estudios empíricos (2015-2025) sobre los procesos formativos de docentes en pensamiento crítico para educación preescolar.',
  },
  {
    id: '3588',
    title: 'Análisis psicométrico de una escala para medir la intención de deserción universitaria: un estudio piloto',
    subtitle: 'Intención de Deserción Universitaria',
    author: 'Euan-Catzín & Canto-Herrera',
    date: 'Noviembre 2025',
    tag: 'Psicometría',
    metric: 91,
    volume: 'Vol. 41',
    abstract: 'Análisis psicométrico piloto de la escala Bäulke para medir la intención de deserción universitaria en estudiantes de Yucatán, México.',
    doi: '10.21555/rpp.3588',
    interactUrl: '#',
    icon: 'Activity',
    color: 'bg-[#be123c]',
    text: 'text-white',
    accent: '#fecdd3',
    keywords: ['deserción', 'psicometría', 'validación', 'méxico', 'yucatán', 'escala Bäulke'],
    hasInteractive: true,
    body: 'Análisis psicométrico piloto de la escala Bäulke para medir la intención de deserción universitaria en estudiantes de Yucatán, México.',
  },
  {
    id: '3604',
    title: 'El cine como mediador pedagógico en la enseñanza de la literatura: aportes desde una experiencia de investigación-acción educativa',
    subtitle: 'El Cine como Mediador Pedagógico',
    author: 'López-Martínez & Muñoz-Madrid',
    date: 'Junio 2026',
    tag: 'Cine y Literatura',
    metric: 91,
    volume: 'Vol. 41',
    abstract: 'Investigación-acción sobre la reconciliación de la palabra escrita con los lenguajes visuales mediante la alfabetización audiovisual en bachillerato.',
    doi: '10.21555/rpp.3604',
    interactUrl: '#',
    icon: 'Film',
    color: 'bg-[#5A5A40]',
    text: 'text-white',
    accent: '#FDFCFB',
    keywords: ['cine', 'literatura', 'alfabetización audiovisual', 'bachillerato', 'investigación acción'],
    hasInteractive: true,
    body: 'Investigación-acción sobre la reconciliación de la palabra escrita con los lenguajes visuales mediante la alfabetización audiovisual en bachillerato.',
  },
  {
    id: '3606',
    title: 'Ajustes razonables y prácticas docentes inclusivas para estudiantes con discapacidad y trastorno del espectro autista en educación superior',
    subtitle: 'Ajustes Razonables en Educación Superior',
    author: 'Macías-Rosado, Ramos-Ramírez & Márquez-Cabellos',
    date: 'Diciembre 2025',
    tag: 'Educación Inclusiva',
    metric: 87,
    volume: 'Vol. 41',
    abstract: 'Estudio cualitativo en la Universidad de Colima sobre ajustes razonables para estudiantes con discapacidad y TEA. Hallazgo: los ajustes dependen de la iniciativa personal docente, no de protocolos institucionales.',
    doi: '10.21555/rpp.3606',
    interactUrl: '#',
    icon: 'Heart',
    color: 'bg-[#1e3a5f]',
    text: 'text-white',
    accent: '#4a9b8e',
    keywords: ['ajustes razonables', 'discapacidad', 'tea', 'educación inclusiva', 'universidad', 'colima'],
    hasInteractive: true,
    body: 'Estudio cualitativo en la Universidad de Colima sobre ajustes razonables para estudiantes con discapacidad y TEA.',
  },
];
